name: DevopsLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.12.0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint the code
        run: npm run lint

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: plokij11/devops1:latest